name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: sudo rm -rf $PWD/* $PWD/.[!.]*
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ishwar-17'

      - name: Configure npm to use GitHub Packages and npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" > ~/.npmrc
          echo "@ishwar-17:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          # echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Publish package to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Publish package to npm
        run: npm publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - run: |
          echo "PACKAGE_VERSION=${{ steps.version.outputs.prop }}" >> $GITHUB_ENV
    
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.version.outputs.prop }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
